
// authors
export const RECEIVE_AUTHORS = "RECEIVE_AUTHORS";
export const RECEIVE_BOOKS_BY_AUTHOR = "RECEIVE_BOOKS_BY_AUTHOR";

// genres
export const RECEIVE_GENRES = "RECEIVE_GENRES";
export const RECEIVE_BOOKS_BY_GENRE = "RECEIVE_BOOKS_BY_GENRE";

// books
export const RECEIVE_BOOKS = "RECEIVE_BOOKS";
export const RECEIVE_ALL_BOOKS = "RECEIVE_ALL_BOOKS";
export const RECEIVE_BOOK = "RECEIVE_BOOK"
export const RECEIVE_BOOK_BY_TITLE = "RECEIVE_BOOK_BY_TITLE"

//cart
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";
