
// authors
export const RECEIVE_AUTHORS = "RECEIVE_AUTHORS";
export const RECEIVE_BOOKS_BY_AUTHOR = "RECEIVE_BOOKS_BY_AUTHOR";

// genres
export const RECEIVE_GENRES = "RECEIVE_GENRES";
export const RECEIVE_BOOKS_BY_GENRE = "RECEIVE_BOOKS_BY_GENRE";
export const RECEIVE_BOOKS_BY_GENRE_IN_STOCK = "RECEIVE_BOOKS_BY_GENRE_IN_STOCK";

// books
export const RECEIVE_BOOKS = "RECEIVE_BOOKS";
export const RECEIVE_ALL_BOOKS = "RECEIVE_ALL_BOOKS";
export const RECEIVE_BOOK = "RECEIVE_BOOK"
export const RECEIVE_BOOK_BY_TITLE = "RECEIVE_BOOK_BY_TITLE"
export const SET_TITLE_SEARCHED = "SET_TITLE_SEARCHED"

//cart
export const ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART";

// comments
export const ADD_COMMENT = "ADD_COMMENT";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";

// transactions
export const ADD_NEW_TRANSACTION = "ADD_NEW_TRANSACTION";
export const REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART";
export const DECREMENT_BOOKS_FROM_CART = "DECREMENT_BOOKS_FROM_CART";
export const INCREMENT_BOOKS_FROM_CART = "INCREMENT_BOOKS_FROM_CART";


//users
export const POST_NEW_USER = "POST_NEW_USER";
export const POST_LOGGIN_USER = "POST_LOGGIN_USER";
export const USER_LOGOUT = "USER_LOGOUT"
