
// authors
export const RECEIVE_AUTHORS = "RECEIVE_AUTHORS";

// genres
export const RECEIVE_GENRES = "RECEIVE_GENRES";
export const RECEIVE_BOOKS = "RECEIVE_BOOKS";
export const RECEIVE_BOOK = "RECEIVE_BOOK"
export const RECEIVE_BOOK_BY_TITLE = "RECEIVE_BOOK_BY_TITLE"
